language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '7'
- '6'
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: kDaSYGv6+r/TezJpoyiYJhITA+DYF5mSh/3eeXXteXImTS45HtE6nKRBYYLcUepGiIbQNcFpZiNROifcVnHHOY64v0h+gst6llPlZ24vp01gOJ6pTZde7+D92yh8la6qsmqmndQ4eF/AndfIoP73p+vpGIg1aSx5W2dhK8IH1efGFSXDmL+DS1LtGRU/a7ZMPE4crWHts2PF5iWnpdT1gVKW0/6HLv7ox70phPXQjqC+UrNlS8BuhcjGJxBFST3NEN5yBqBNveNiZHvJwQUt8R0gAkLATTTjV8fyDt+WL7OOQ9/Xq+51eLMSmfNuORci4y/7bj6FGtSDmZI+wwK9zb0Mg/zruGHbWhAJ2B1cTArp3RI2yKF2wDwFwbdO5cQo8fKBidC5Fe6qoiFVxwWUXfFfkDmHmK5CD0EMX8fJS00gt4l62vfydX6XqQj3gl7z1CixX4jlrJTQqa1fKbQwyDACsLDlGzlVk3d5wynQbdwvWYTtMke1P1i6IN+on5MqGxljo8lL9//Lfrp/Tv3YR73oNRa+P4vUsGHg7Bx2aO4etLTs0yljxdDkswC2rqkyp2M4KMVmQhpLtLygZshjT0wtnluqykOCP5RihqPsMhfWqJMSINFVklKFlQN5eb5j3XB4rj4XSgOhix7/7IniQWEK5jhejAn2Gipp3N8i18g=
