language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '7'
- '6'
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: OeAT3C5bCXgx1bmeltKJsY7MVnWrLL/3UmcTORTqOZKpkTILBOSQfi7fNkT+NMO6/36W36BhEU7oKNa+Oo/jpZFwcC8qIZBOMpD0WR0eMY/iXxveAt7QUtePFOfZZIdNjZZgmlpHaZeCPuyH9etxwhmLomS9wDxyLYwzxHRTwwLhPTgQVXRi+aM7Rs9MfFYgeHN6fyz9aikBuiOFefg31XAgT8XwXP9M3vU2/dmP9nZU2RjeB5UcPifK1Qa79Myq+lbhurLnBf9nKAOF+Mw+7pVT3PvxSrGVLdyVBSc354CLdsezzA4qMgeb8D8XxaUjfKYqaxqPcO28rEd5MOWZMxf62heY+aXV7n5UVBlPK+/YUnXQGeNEK2bqan/kY2iFGKAUJMeIcwSGvqaNpD+p1XDWRVcM8C92dmtkaSJmlmVxhSMUJlO7r6HyxJJMobDlVN/XcdW66GC4cVwQ2iDrWQkzJS/RQj673qkIO1RYk9hh7IEAFQLAhMecDV/cFiRmnrgw1AdmZ8FIA5yVrSiEo54i1y5Dn1vBuxCMN65SLJuQG4ZFx2tttCS30tL1P5C2H6LkB2lTyeXlYloQTC/TPZusndCrL7SQzAnXCUOgHiK6wJiZfbOmt90Tv/LpPBlrzRzLGOHAdZDgsLm1fLLsrNBrCP6o6np92URrhO0hakQ=
